### ISSUE TITLE
Unix release

### ISSUE THREAD

**Issue by bcbernardo** [davidrusu/cactus-releases#3]
Hi! Congratulations for the app.

As a Unix (Fedora) user, I'm curious to know whether a Linux release is anywhere in the roadmap... As far as I could google, there is no other random sampling app that support Unix systems yet, and it would be great if Cactus did.

**Comment by davidrusu** [comment]
Hey @bcbernardo, I run nix personally for development of Cactus, but had been stalling on putting up releases for linux since the fragmentation across distros was a little daunting.

I'll take a look around to see how feasible this is, I'll let you know what I find.

**Comment by davidrusu** [comment]
@bcbernardo [1.7.3](https://github.com/davidrusu/cactus-releases/releases/tag/v1.7.3) has a new AppImage release, I think it should work across most linux distros. Let me know if you run into any trouble.

**Comment by bcbernardo** [comment]
The AppImage works like a charm in Fedora 33. Thanks for taking the time to look at this!
